# net_retrofit_kit code generation: generate implementation classes (.g.dart)
# for abstract classes annotated with @NetApi.
# Run this in example apps or downstream projects:
# dart run build_runner build --delete-conflicting-outputs

builders:
  net_retrofit_kit:
    import: "package:net_retrofit_kit/src/generate/build.dart"
    builder_factories: ["netRetrofitBuilder"]
    build_extensions: {".dart": [".net_retrofit_kit.g.part"]}
    applies_builders: ["source_gen|combining_builder"]
    build_to: cache
    auto_apply: dependents
